### ISSUE TITLE
Marker icons are cut on the edges of map canvas tiles

### ISSUE THREAD

**Issue by Raruto** [Raruto/leaflet-kmz#2]
This problem occurs when using/activating the **geojson-vt.js** library

![clipped-markers](https://user-images.githubusercontent.com/9614886/57689747-6706e380-7640-11e9-9a5d-6a03063fdf8a.jpg)

Apparently all the icons wich insist on two tiled canvas are cutted

![clipped-markers](https://user-images.githubusercontent.com/9614886/57689748-6706e380-7640-11e9-91f3-be9ae475386e.jpg)

But, in this image, the icon circled in yellow does not seem to suffer of these kind of problems...

---

You can see this problem in action directly in this [example](https://raruto.github.io/examples/leaflet-kmz/leaflet-kmz.html) and adding the following portion of css code:

```css 
.leaflet-tile-container canvas {
    border: 1px solid #fff; /* show map tiles grid borders */
}
```

---

_if you have any **suggestions on how to solve** this annoying problem, please fork and commit!_
